health_and_fitness/health_and_fitness/diet/urls.py
from django.conf.urls import url

from diet import views

urlpatterns = [
     url(r'^(?P<diet_id>[0-9]+)/', views.diet ,name = 'diet'),
     url(r'meal/rate/', views.rate_meal,name = 'rate_meal'),   
     url(r'rate/', views.rate_diet ,name = 'rate_diet'),     
     url(r'meal/add_com/', views.meal_add_com ,name = 'meal_add_com'),
     url(r'ingre/add_com/', views.ingre_add_com ,name = 'ingre_add_com'),
     url(r'add_com/', views.diet_add_com ,name = 'diet_add_com'),
     url(r'meal/(?P<meal_id>[0-9]+)/', views.meal ,name = 'meal'),
     url(r'meals/', views.meals ,name = 'meals'),
     url(r'ingres/', views.ingres ,name = 'ingres'),
     url(r'ingre/(?P<ingre_id>[0-9]+)/', views.ingre ,name = 'ingre'),

     url(r'add_unit/', views.add_unit ,name = 'add_unit'),
     url(r'add_ingre_type/', views.add_ingre_type, name = 'add_ingre_type'),
     url(r'add_ingre/', views.add_ingre, name = 'add_ingre'),
     url(r'add_meal_type/', views.add_meal_type, name = 'add_meal_type'),
     url(r'add_recipe/', views.add_recipe ,name = 'add_recipe'),
]

health_and_fitness/health_and_fitness/health_and_fitness/urls.py
from datetime import datetime
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from diet import views
from django.views.static import serve


urlpatterns = [
     url(r'^forum/',  include('forum.urls')),
     url(r'^user/',  include('accounts.urls')),
     url(r'^diet/',  include('diet.urls')),
     url(r'^admin/', include(admin.site.urls)),

     url(r'^register/$', views.register ,name = 'register'),
     url(r'^login/$', views.login ,name = 'login'),
     url(r'^logout/$', views.logout ,name = 'logout'),
     url(r'^$', views.index ,name = 'index'),
     url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
]

health_and_fitness/health_and_fitness/diet/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
import json

class JSONObjects(object):
    def __init__(self, obj):
        self.Name           = obj.Name
        self.ID             = obj.id
        self.Creation_Data  = obj.Creation_Data.strftime('%m/%d/%Y %H:%M:%S')
        self.Creator        = obj.Creator.username

    def __unicode__(self):
        return json.dumps(self.__dict__) 

    def __str__(self):
        return self.__unicode__()

class JSONObjectsD(JSONObjects):
    def __init__(self, obj):
        self.Description    = obj.Description
        super(JSONObjectsD, self).__init__(obj)


class JSONObjectsT(JSONObjectsD):
    def __init__(self, obj):
        self.Types = [ t.get_json() for t in obj.Types.all()]
        super(JSONObjectsT, self).__init__(obj)
    

class IngredientType(models.Model):
    Name            = models.CharField(max_length = 64, null = False, blank = False, unique = True)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Description     = models.TextField(default= "", null = True, blank = True)

    def __unicode__(self):
        return self.Name

    def get_json(self):
        return str(JSONObjectsD(self))

class Ingredient(models.Model):
    Image           = models.ImageField(upload_to='ingre_image/', default ='ingre_image/default.jpg')
    Name            = models.CharField(max_length = 64, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Description     = models.TextField(default= "", null = True, blank = True)
    Types           = models.ManyToManyField(IngredientType)

    def __unicode__(self):
        return self.Name

    class JSONIngredient(JSONObjectsT):
        def __init__(self, obj):
            self.Types = list(obj.Types.values_list('id','Name'))
            self.Image = obj.Image.url
            super(Ingredient.JSONIngredient, self).__init__(obj)

    def get_json(self):
        return str(Ingredient.JSONIngredient(self))


class IngredientComment(models.Model):
    Content         = models.TextField(default= "", null = False, blank =False)
    Author          = models.ForeignKey(User, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Ingredient            = models.ForeignKey(Ingredient, null = False, blank = False)

    def reference(self):
        return self.Ingredient

    def get_admin_url(self):
        return '/admin/diet/ingredientcomment/%s/' % self.id


class Unit(models.Model):
    Name            = models.CharField(max_length = 64, null = False, blank = False, unique = True)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)

    def __unicode__(self):
        return self.Name

    def get_json(self):
        return str(JSONObjects(self))

class FoodIngredient(models.Model):
    Ingredient      = models.ForeignKey(Ingredient, null = False, blank = False)
    Number          = models.FloatField(default = 0.0)
    Unit            = models.ForeignKey(Unit, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)

    def __unicode__(self):
        return '%s %s of %s' % (self.Number, self.Unit, self.Ingredient)

class MealType(models.Model):
    Name            = models.CharField(max_length = 64, null = False, blank = False, unique = True)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Description     = models.TextField(default= "", null = True, blank = True)

    def __unicode__(self):
        return self.Name

    def get_json(self):
        return str(JSONObjectsD(self))


class Meal(models.Model):
    Image           = models.ImageField(upload_to='meals_image/', default ='meals_image/default.jpg')
    Name            = models.CharField(max_length = 64, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Description     = models.TextField(default= "", null = True, blank = True)
    Ingredients     = models.ManyToManyField(FoodIngredient)
    Types           = models.ManyToManyField(MealType)
    Time            = models.IntegerField(default = 0) 
    Rating          = models.IntegerField(default = 0)
    Rating_Count    = models.IntegerField(default = 0)
    Difficulty      = models.IntegerField(default = 0)
    c_ratting        = models.FloatField(default = 0)
    Voters          = models.ManyToManyField(User, blank = True, related_name='voters_meal')


    def get_rating(self):
        if self.Rating_Count == 0:
            return 0
        return self.Rating/ float(self.Rating_Count)

    def get_time(self):
        return '%s m' % self.Time

    def __unicode__(self):
        return self.Name

    def save(self, force_insert = False, force_update = False, using = None, update_fields = None):
        self.c_ratting = self.get_rating()
        return super(Meal, self).save(force_insert, force_update, using, update_fields)

    def rating_enable(self, user):
        return not self.Voters.filter(id = user.id).exists()

    def add_rating(self, user, rating):
        self.Rating+= rating
        self.Rating_Count+=1
        self.Voters.add(user)
        self.save()

class MealComment(models.Model):
    Content         = models.TextField(default= "", null = False, blank =False)
    Author          = models.ForeignKey(User, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Meal            = models.ForeignKey(Meal, null = False, blank = False)

    def reference(self):
        return self.Meal

    def get_admin_url(self):
        return '/admin/diet/mealcomment/%s/' % self.id


class DietType(models.Model):
    Name            = models.CharField(max_length = 64, null = False, blank = False, unique = True)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Description     = models.TextField(default= "", null = True, blank = True)

    def __unicode__(self):
        return self.Name


class Diet(models.Model):
    Name            = models.CharField(max_length = 64, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Creator         = models.ForeignKey(User, null = False, blank = False)
    Meals           = models.ManyToManyField(Meal)
    Types           = models.ManyToManyField(DietType)
    Description     = models.TextField(default= "", null = True, blank = True)
    Rating          = models.IntegerField(default = 0)
    Rating_Count    = models.IntegerField(default = 0)
    Voters          = models.ManyToManyField(User, blank = True, related_name='voters_diet')

    def get_rating(self):
        if self.Rating_Count == 0:
            return 0
        return self.Rating/ float(self.Rating_Count)

    def __unicode__(self):
        return self.Name

    def rating_enable(self, user):
        return not self.Voters.filter(id = user.id).exists()

    def add_rating(self, user, rating):
        self.Rating+= rating
        self.Rating_Count+=1
        self.Voters.add(user)
        self.save()


class DietComment(models.Model):
    Content         = models.TextField(default= "", null = False, blank =False)
    Author          = models.ForeignKey(User, null = False, blank = False)
    Creation_Data   = models.DateTimeField(default = timezone.now)
    Diet            = models.ForeignKey(Diet, null = False, blank = False)

    def reference(self):
        return self.Diet

    def get_admin_url(self):
        return '/admin/diet/dietcomment/%s/' % self.id

health_and_fitness/health_and_fitness/diet/templates/comment_list_admin.html
<table>   
    {% for comment in comments %}
        <tr>
            <td style="width: 150px;"><a href="{{ comment.get_admin_url }}"><div>{{ comment.Author }}</div><div style="font-size: 12px;">{{ comment.Creation_Data }}</div></a></td>
                <td><div style="text-align: left;  ">{{ comment.Content }}</div></td> 
        </tr>
    {% endfor %}
</table>

health_and_fitness/health_and_fitness/diet/templates/diet.html
<div style="background-color: dimgrey; width:1000px; text-align:left; color:white; font-size: 20px;">
     <div style="background-color:cornflowerblue; width:980px; text-align:left; color:white; margin-left:10px;">
        <div>
            <table style="width: 100%;">
                <tr>
                    <td>
                        <p style="font-size: 30px;">{{ diet.Name}}</p>
                    </td>
                    <td style="height: 100px; width: 100px;" class="tooltip">
                        {% if is_favorite %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="remove_from_f" />
                                <input  type="image" src="/media/heart_on.png" alt="REMOVE FROM FAVORITES" style="width:100px;height:100px;" />
                                <span class="tooltiptext">REMOVE FROM FAVORITES</span>
                            </form>

                        {% else %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="add_to_f" />
                                <input  type="image" src="/media/heart_off.png" alt="ADD TO FAVORITES" style="width:100px;height:100px;"/>
                                <span class="tooltiptext">ADD TO FAVORITES</span>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
         <div>{{ diet.Creation_Data }}</div>
         <div>{{ diet.Creator }}</div>
         <div>RATING: {{ diet.get_rating }}</div>
         <div>
              {%for type in diet.Types.all %}
              {{ type }}
              {% endfor %}
         </div>         
         <div style="background-color: dodgerblue;">
             {{ diet.Description}}
         </div>
            MEALS:
            <table style="width: 100%; margin-top: 20px;">
            <tr style="height: 50px; background-color:navy;">
                <td></td>
                <td>NAME</td>
                <td>CREATOR</td>
                <td>RATING</td>
                <td>TYPES</td>
                <td>TIME</td>
                <td>DIFFICULTY</td>
                <td>INGREDIENTS</td>
            </tr>
            {% for meal in diet.Meals.all %}
            <tr class="tooltip">
                <td><a href="/diet/meal/{{meal.id}}/"> <img src="/media/{{meal.Image}}" alt="{{ meal.Name }}" style="width:50px;height:50px;"/></a>
                <span class="tooltiptext"> {{ meal.Description }}</span>
                </td>
                <td> <a href="/diet/meal/{{meal.id}}/">{{ meal.Name }}</a></td>
                <td> {{ meal.Creator}}    </td>
                <td> {{ meal.get_rating}} </td>
                <td>  {% for type in meal.Types.all%}
                      <div class="tooltip">{{type}}
                      <span class="tooltiptext"> {{ type.Description }}</span>
                      </div>
                      {% endfor%}
                </td>
                <td>{{ meal.get_time }} </td>
                <td>{{ meal.Difficulty}}</td>
                <td>{{ meal.Ingredients.count }}</td>
            </tr>
            {% endfor %}
            </table>


    </div>
   {% if user.is_authenticated and rating_enable %}
    <center>
        <div style="background-color:lightskyblue; width: 500px; color:black; margin-top: 50px;">
            <center>
            <form action="/diet/rate/" method="post">
                {% csrf_token %}
                <input type="hidden"  name="id" value="{{diet.id}}"/>
                <table>
                    <tr>
                        <td><input type="radio" name="rate" value="1" />1</td>
                        <td><input type="radio" name="rate" value="2" />2</td>
                        <td><input type="radio" name="rate" value="3" />3</td>
                        <td><input type="radio" name="rate" value="4" />4</td>
                        <td><input type="radio" name="rate" value="5" />5</td>
                        <td><input type="radio" name="rate" value="6" />6</td>
                        <td><input type="submit" value="RATE" /></td>
                    </tr>
                </table>
            </form>
            </center>
        </div>
    </center>
    {% endif %}


    <div style="margin-top:20px;">
    <center>
        <table style="width: 90%;">
            {% for comm in diet.dietcomment_set.all %}
                <tr>
                    <td> <div>{{ comm.Author }}</div><div> {{ comm.Creation_Data}}</div></td>
                    <td>{{ comm.Content }}</td>
                </tr>
            {% endfor%}
        </table>
    </center>
    </div>
        
    {% if user.is_authenticated %}
    <center>
        <div style="background-color:lightskyblue; width: 500px; color:black; margin-top: 50px;">
            <center>
            <form action="/diet/add_com/" method="post">
                {% csrf_token %}
                <input type="hidden"  name="id" value="{{diet.id}}"/>
                <textarea style="width:400px; height: 100px;" name="content"></textarea> 
                <input type="submit" value="ADD COMMENT" />
            </form>
            </center>
        </div>
    </center>
    {% endif %}
</div>

health_and_fitness/health_and_fitness/diet/templates/diets.html
<div style="background-color: dimgrey; width:1000px; text-align:left; color:white; margin-top: 70px; font-size: 20px;">
    <div style="background-color:cornflowerblue; width:980px; text-align:left; color:white; margin-left:10px;">
        <center>
            <table style="width: 100%;">
            <tr style="height: 50px; background-color:navy;">
                <td>NAME</td>
                <td>CREATOR</td>
                <td>RATING</td>
                <td>TYPES</td>
            </tr>
            {% for diet in diets %}
            <tr class="tooltip">
                <td> <a href="/diet/{{diet.id}}/">{{ diet.Name }}</a>
                <span class="tooltiptext"> {{ diet.Description }}</span>
                </td>
                <td> {{ diet.Creator}}    </td>
                <td> {{ diet.get_rating}} </td>
                <td>  {% for type in diet.Types.all%}
                      {{type}}
                      {% endfor%}
                </td>
            </tr>
            {% endfor %}
            </table>
        </center>
    </div>
        <div>
        <center>
        <table>
            <tr>
                {% for page in pages %}
                {% if page != current_page %}
                <td>
                    <form action="/" method="get">
                    <input type="hidden"  value="{{ page }}" name="page"/>
                    <input type="submit" value="{{ page}}" />
                    </form>
                </td>
                {% else %}
                <td>
                    <input type="submit" value="{{ page}}" style="color:white; background-color:black;" />
                </td>
                {% endif %}
                {% endfor %}
            </tr>
        </table>
        </center>
    </div>    
</div>

health_and_fitness/health_and_fitness/diet/templates/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Health &amp; Fitness</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

</head>
<body>   
        <div id="top_nav" >
            <ul id="top_nav_ul">
                <li id="top_nav_left"><a href="/" id="top_nav_a">DIETS</a></li>
                <li id="top_nav_left" style="width: 110px;"><a href="/diet/meals" id="top_nav_a">MEALS</a></li>
                <li id="top_nav_left" style="width: 190px;"><a href="/diet/ingres" id="top_nav_a">INGREDIENTS</a></li>
                <li id="top_nav_left"><a href="/forum" id="top_nav_a">FORUM</a></li>
                {% if user.is_authenticated %}
                <li id="top_nav_right" style="width: 180px;"><a href="/logout" id="top_nav_a">LOGOUT</a></li> 
                <li id="top_nav_right" style="width: 250px;"><a href="/user" id="top_nav_a">YOUR ACCOUNT</a></li> 

                {% else %}
                <li id="top_nav_right"><a href="/login" id="top_nav_a">LOGIN</a></li>
                <li id="top_nav_right"><a href="/register" id="top_nav_a">REGISTER</a></li>
                {% endif %}
            </ul>
        </div>
        <div id="content">
            <center>
            {% autoescape off %}
            {{ content }}
            {% endautoescape %}
            </center>
        </div>
</body>
</html>

health_and_fitness/health_and_fitness/diet/templates/ingre.html
<div style="background-color: dimgrey; width:1000px; text-align:left; color:white; font-size: 20px;">
     <div style="background-color:cornflowerblue; width:980px; text-align:left; color:white; margin-left:10px;">
        <p style="font-size: 30px;"> <img src="/media/{{ingre.Image}}" alt="{{ ingre.Name }}" style="width:100px;height:100px;"/>{{ingre.Name}} </p>
         <div>{{ ingre.Creation_Data }}</div>
         <div>{{ ingre.Creator }}</div>
         <div>
              {%for type in ingre.Types.all %}
              {{ type }}
              {% endfor %}
         </div>
         <div style="background-color: dodgerblue;">
             {{ ingre.Description}}
         </div>
    </div> 
    <div style="margin-top:20px;">
    <center>
        <table style="width: 90%;">
            {% for comm in ingre.ingredientcomment_set.all %}
                <tr>
                    <td> <div>{{ comm.Author }}</div><div> {{ comm.Creation_Data}}</div></td>
                    <td>{{ comm.Content }}</td>
                </tr>
            {% endfor%}
        </table>
    </center>
    </div>
        
    {% if user.is_authenticated %}    
    <center>
        <div style="background-color:lightskyblue; width: 500px; color:black; margin-top: 50px;">
            <center>
            <form action="/diet/ingre/add_com/" method="post">
                {% csrf_token %}
                <input type="hidden"  name="id" value="{{ingre.id}}"/>
                <textarea style="width:400px; height: 100px;" name="content"></textarea> 
                <input type="submit" value="ADD COMMENT" />
            </form>
            </center>
        </div>
    </center>
    {% endif %}
</div>

health_and_fitness/health_and_fitness/diet/templates/ingres.html
<div style="background-color: dimgrey; width:1000px; text-align:left; color:white; margin-top: 70px; font-size: 20px;">
    <div style="background-color:cornflowerblue; width:980px; text-align:left; color:white; margin-left:10px;">
        <center>
            <table style="width: 100%; ">
            <tr style="height: 50px; background-color:navy;">
                <td></td>
                <td>NAME</td>
                <td>CREATOR</td>
                <td>TYPES</td>
            </tr>
            {% for ingre in ingres %}
            <tr class="tooltip">
                <td><a href="/diet/ingre/{{ingre.id}}/"> <img src="/media/{{ingre.Image}}" alt="{{ ingre.Name }}" style="width:50px;height:50px;"/></a>
                <span class="tooltiptext"> {{ ingre.Description }}</span>
                </td>
                <td> <a href="/diet/ingre/{{ingre.id}}/">{{ ingre.Name }}</a></td>
                <td> {{ ingre.Creator}}    </td>
                <td>  {% for type in ingre.Types.all%}
                      <div>{{type}}</div>
                      {% endfor%}
                </td>
            </tr>
            {% endfor %}
            </table>
        </center>
    </div>
        <div>
        <center>
        <table>
            <tr>
                {% for page in pages %}
                {% if page != current_page %}
                <td>
                    <form action="/diet/ingres/" method="get">
                    <input type="hidden"  value="{{ page }}" name="page"/>
                    <input type="submit" value="{{ page}}" />
                    </form>
                </td>
                {% else %}
                <td>
                    <input type="submit" value="{{ page}}" style="color:white; background-color:black;" />
                </td>
                {% endif %}
                {% endfor %}
            </tr>
        </table>
        </center>
    </div>    
</div>

health_and_fitness/health_and_fitness/diet/templates/login.html
<div style="background-color: dimgrey; width:500px; text-align:left; color:white;">
    {% for error in errors %}
    <div style="background-color:red; color:black; text-align:center;">{{ error }}</div>
    {% endfor %}

    <form method="post" action="/login/">
        {% csrf_token %}
        <table>
            <tr>
                <td style="width:250px">USERNAME</td>
                <td><input type="text" name="username" style="width:250px"/></td>
            </tr>
            <tr>
                <td style="width:250px">PASSWORD</td>
                <td><input type="password" name="password" style="width:250px" /></td>
            </tr>
            <tr>
                <td style="width:250px" ></td>
                <td><input type="submit" value="LOGIN" style="width:200px; margin-left:25px;"/></td>
            </tr>
        </table>         
    </form>
</div>

health_and_fitness/health_and_fitness/diet/templates/meal.html
<div style="background-color: dimgrey; width:1000px; text-align:left; color:white; font-size: 20px;">
     <div style="background-color:cornflowerblue; width:980px; text-align:left; color:white; margin-left:10px;">
         <div>
            <table style="width: 100%;">
                <tr>
                    <td style="height: 100px; width: 100px;">
                        <img src="/media/{{meal.Image}}" alt="{{ meal.Name }}" style="width:100px;height:100px;"/>
                    </td>
                    <td>
                        <p style="font-size: 30px;">{{ meal.Name}}</p>
                    </td>
                    <td style="height: 100px; width: 100px;" class="tooltip">
                        {% if is_favorite %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="remove_from_f" />
                                <input  type="image" src="/media/heart_on.png" alt="REMOVE FROM FAVORITES" style="width:100px;height:100px;" />
                                <span class="tooltiptext">REMOVE FROM FAVORITES</span>
                            </form>
                        {% else %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="add_to_f" />
                                <input  type="image" src="/media/heart_off.png" alt="ADD TO FAVORITES" style="width:100px;height:100px;"/>
                                <span class="tooltiptext">ADD TO FAVORITES</span>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            </table>
         </div>
         <div>{{ meal.Creation_Data }}</div>
         <div>{{ meal.Creator }}</div>
         <div>RATING    : {{ meal.get_rating }}</div>
         <div>TIME      : {{ meal.get_time}}</div>
         <div>DIFFICULTY: {{ meal.Difficulty}}</div>
         <div>
              {%for type in meal.Types.all %}
             <div class="tooltip">
                {{ type }}
                 <span class="tooltiptext">{{type.Description}}</span>
              </div>
              {% endfor %}
         </div>         
         <div style="background-color: dodgerblue;">
             {{ meal.Description}}
         </div>
        <table style="width: 100%; margin-top: 20px;">   
        {% for ingre in meal.Ingredients.all %}
            <tr style="height:40px;" class="tooltip">
                <td><a href="/diet/ingre/{{ingre.id}}">{{ ingre.Ingredient }}</a>
                <span class="tooltiptext">{{ ingre.Ingredient.Description}}</span>
                </td>
                <td><div style="text-align: left; ">{{ ingre.Number  }}</div></td> 
                <td><div style="text-align: left; ">{{ ingre.Unit }}</div></td> 
            </tr>
        {% endfor %}
        </table>
    </div>

    {% if user.is_authenticated and rating_enable %}
    <center>
        <div style="background-color:lightskyblue; width: 500px; color:black; margin-top: 50px;">
            <center>
            <form action="/diet/meal/rate/" method="post">
                {% csrf_token %}
                <input type="hidden"  name="id" value="{{meal.id}}"/>
                <table>
                    <tr>
                        <td><input type="radio" name="rate" value="1" />1</td>
                        <td><input type="radio" name="rate" value="2" />2</td>
                        <td><input type="radio" name="rate" value="3" />3</td>
                        <td><input type="radio" name="rate" value="4" />4</td>
                        <td><input type="radio" name="rate" value="5" />5</td>
                        <td><input type="radio" name="rate" value="6" />6</td>
                        <td><input type="submit" value="RATE" /></td>
                    </tr>
                </table>
            </form>
            </center>
        </div>
    </center>
    {% endif %}

    <div style="margin-top:20px;">
    <center>
        <table style="width: 90%;">
            {% for comm in meal.mealcomment_set.all %}
                <tr>
                    <td> <div>{{ comm.Author }}</div><div> {{ comm.Creation_Data}}</div></td>
                    <td>{{ comm.Content }}</td>
                </tr>
            {% endfor%}
        </table>
    </center>
    </div>
        
    {% if user.is_authenticated %}    
    <center>
        <div style="background-color:lightskyblue; width: 500px; color:black; margin-top: 50px;">
            <center>
            <form action="/diet/meal/add_com/" method="post">
                {% csrf_token %}
                <input type="hidden"  name="id" value="{{meal.id}}"/>
                <textarea style="width:400px; height: 100px;" name="content"></textarea> 
                <input type="submit" value="ADD COMMENT" />
            </form>
            </center>
        </div>
    </center>
    {% endif %}
</div>

health_and_fitness/health_and_fitness/diet/templates/register.html
<div style="background-color: dimgrey; width:500px; text-align:left; color:white;">
    {% for error in errors %}
    <div style="background-color:red; color:black; text-align:center;">{{ error }}</div>
    {% endfor %}

    <form method="post" action="/register/">
        {% csrf_token %}
        <table>
            <tr>
                <td style="width:250px">USERNAME</td>
                <td><input type="text" name="username" style="width:250px"/></td>
            </tr>
            <tr>
                <td style="width:250px">PASSWORD</td>
                <td><input type="password" name="password" style="width:250px" /></td>
            </tr>
            <tr>
                  <td style="width:250px">EMAIL</td>
                  <td><input type="email" name="email" style="width:250px" /></td>
            </tr>
            <tr>
                <td style="width:250px" ></td>
                <td><input type="submit" value="REGISTER" style="width:200px; margin-left:25px;"/></td>
            </tr>
        </table>         
    </form>
</div>